name: CI

on:
  push:
    branches:
      - master
      - release-*
    tags: '*'
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    # Allow failure on nightly
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.2'
          - '1.5'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        arch:
          - x86
          - x64
        exclude:
          # No macOS on x86
          - {os: 'macos-latest', arch: 'x86'}
          # Reduce number of runs on older versions
          - {os: 'windows-latest', version: '1.2'}
          - {os: 'windows-latest', version: '1.5'}
          - {os: 'windows-latest', version: 'latest'}
          - {os: 'macos-latest', version: '1.2'}
          - {os: 'macos-latest', version: '1.5'}
          - {os: 'macos-latest', version: 'latest'}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
